version: '3.8'

services:
  proxy-service:
    build: .
    container_name: tmdb-proxy-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped 